//
//  APIClient.swift
//  BlueLagoonMobile
//
//  Created by Azoulay ben on 25/09/2019.
//  Copyright © 2019 Benazoulaydev. All rights reserved.
//

import Foundation
import UIKit
class APIClient {
    func getData() ->[WeatherItem] {
        var array: [WeatherItem] = [WeatherItem]()
        let item1 = WeatherItem(image:UIImage.init(named: "hurricane"), text:"Hurricanes & Typhoons", textDescription:"If a hurricane is likely in your area, you should: ", textView:"- Stay informed by monitoring the storm via local radio, NOAA radio, TV, and internet. Listen for alerts to evacuate.",textView1:"- Secure your home and close storm shutters. Even awnings can be broken and picked up by strong winds and potentially become a projectile.",textView2:"- Bring all lawn furniture, grills, trash barrels, bikes, hanging plants, toys, and gardening tools inside or tied down in a secure spot. ",textView3:"- Turn off utilities if instructed by authorities to do so. Otherwise, turn the refrigerator and freezer thermostat to its coldest setting and keep its doors closed.",textView4:"- Move freezable items from the fridge to the freezer.",textView5:"- Do NOT drive or walk through floodwaters which may be electrically-charged and filled with contaminants; just six inches of moving flood water will knock a grown man down." )
        let item2 = WeatherItem(image:UIImage.init(named: "tornado"), text:"Cyclones" , textDescription:"Tip Cyclones",  textView:"- Don’t panic. ",textView1:"- Make sure you are in a safe position to offer help. DO NOT attempt to assist victims if you are in danger (for example, the building is on fire, traffic has not been controlled, or guns are being fired etc.).",textView2:"- Remember the ABCs of Life Support Airways open—Open and maintain victim’s airway. Breathing restored—If victim is not breathing, then begin rescue-breathing techniques immediately. ",textView3:"Circulation maintained—If no pulse is present, call 911 or your local Emergency Medical Services (EMS) and then get assistance from a person certified in cardiopulmonary resuscitation (CPR) techniques. REMEMBER, to be able to perform CPR effectively, it is essential to be properly trained.",textView4:"- Look for signs of shock and broken bones or fractures.",textView5:"- Check for bleeding. Apply direct pressure with a clean cloth and seek medical attention as soon as possible. If possible, wear health care gloves to protect yourself from direct contact with blood.")
        let item3 = WeatherItem(image:UIImage.init(named: "earthquake"), text:"Earthquakes", textDescription:"Drop, Cover and Hold On!", textView:"-If you are in a vehicle, pull over and stop. Set your parking brake." ,textView1:"- If you are in bed, turn face down and cover your head and neck with a pillow.",textView2:"- If you are outdoors, stay outdoors away from buildings.",textView3:"- Do not get in a doorway.",textView4:"-Do not run outside.",textView5:"If an earthquake happens, protect yourself right away")
        let item4 = WeatherItem(image:UIImage.init(named: "tsunami"), text:"Tsunami", textDescription:"Drop to your hands and knees. Cover ", textView:"- If you are outside of the tsunami hazard zone and receive a warning, then stay where you are unless officials tell you otherwise.",textView1:"- When the shaking stops, if there are natural signs or official warnings of a tsunami, then move immediately to a safe place as high and as far inland as possible",textView2:"- If you are outside of the tsunami hazard zone and receive a warning, then stay where you are unless officials tell you otherwise.",textView3:"- Leave immediately if you are told to do so. Evacuation routes are often marked by a wave with an arrow in the direction of higher ground.",textView4:"- If you are in the water, then grab onto something that floats, such as a raft, tree trunk, or door.",textView5:"- If you are in a boat, then face the direction of the waves and head out to sea. If you are in a harbor, then go inland.")
        let item5 = WeatherItem(image:UIImage.init(named: "flood"), text:"Flood", textDescription:"When a flood warning is issued for your area, evacuate", textView:"- If you have time prior to evacuation, secure your home. Bring in outdoor furniture. Move essential items to the highest part of the upper floor of your home.",textView1:"- Turn off utilities at the main switches or valves if instructed to do so. Disconnect electrical appliances. Do not touch electrical equipment if you are wet or standing in water",textView2:"- Do not walk through moving water. Six inches of moving water can sweep you off your feet. If you have to walk in water, walk where the water is not moving. Use a stick to check the firmness of the ground in front of you.",textView3:"- Turn around, don’t drown! If you come upon a flowing stream where water is above your ankles, stop, turn around and go another way. People underestimate the force and power of water.",textView4:"- Keep children out of the water.",textView5:" ")
        let item6 = WeatherItem(image:UIImage.init(named: "storm"), text:"Storm", textDescription:"Tip Storm", textView:"- Monitor your NOAA Weather Radio or local radio and/or TV station for information and emergency instructions",textView1:"- Have your emergency survival kit ready to go if told to evacuate",textView2:"- If advised to evacuate, tell others where you are going, turn off utilities if told to, then leave immediately, following routes designated by local officials",textView3:"- If you go outside for any reason, dress for expected conditions.",textView4:"- For cold weather, wear several layers of loose-fitting, lightweight, warm clothing rather than one layer of heavy clothing. ",textView5:"Mittens are warmer than gloves. ")
        array.append(item1)
        array.append(item2)
        array.append(item3)
        array.append(item4)
        array.append(item5)
        array.append(item6)
        return array
    }
}
